@startuml act
title Diagramme d'Activité — Import Automatisé TMDB (ImportMoviesCommand)

skinparam shadowing false
skinparam RoundCorner 5
skinparam ArrowColor #333333
skinparam ActivityBackgroundColor #E8DAEF
skinparam ActivityBorderColor #8E44AD

start
:Importation manuelle des films via la commande;
:Récupération de la liste complète des genres;

while (Reste-t-il des pages à traiter ?) is (Oui)
    :Appel API TMDB pour la page;
    
    while (Reste-t-il des films sur cette page ?) is (Oui)
        :Récupération des plateformes de streaming;
        :Récupération des vidéos;
        
        if (Film sorti ? ET A des plateformes ? ET A un trailer (FR/EN) ?) then (Non)
            if (Le film existait déjà en BDD ?) then (Oui)
                :Suppression du film de la BDD;
            else (Non)
            endif
            :Ignorer ce film;
            
        else (Oui, film valide)
            if (Le film existe déjà dans la BDD ?) then (Oui)
                :Nettoyage complet de ses relations existantes;
            else (Non)
                :Création d'une nouvelle entité Movie;
            endif
            
            :Mise à jour des informations basiques;
            
            :Appel API TMDB pour la durée exacte;
            :Mise à jour de la durée;
            
            :Création/Association des entités Genre;
            :Création/Association des entités Platform;
            
            :Appel API TMDB pour le Casting;
            :Création/Association des acteurs;
            
            :Préparation à la sauvegarde;
        endif
    endwhile (Non)
    
    :Sauvegarde en BDD;
    :Libération de la mémoire RAM;
endwhile (Non)

:Affichage du message de succès dans la console;
stop

@enduml
