@startuml act3
title Diagramme d'Activité — Système de Recommandation Personnalisé

skinparam shadowing false
skinparam RoundCorner 5
skinparam ArrowColor #333333
skinparam ActivityBackgroundColor #FCF3CF
skinparam ActivityBorderColor #F39C12

start
:Appel de la route GET /recommendations/for-you;
:Vérification du token JWT de l'utilisateur;
:Extraction des préférences utilisateur\n(Genres favoris, Plateformes);
:Extraction des films de sa Watchlist;

:Analyse de la Watchlist;
:Déduction des "genres implicites" (Top 3 les plus regardés);

:Récupération de tous les films de la BDD;

while (Reste-t-il des films à analyser ?) is (Oui)
    if (Le film est déjà dans la Watchlist ?) then (Oui)
        :Ignorer le film (continue);
    else (Non)
        :Initialiser Score = 0;
        
        if (Le film contient un genre favori explicite ?) then (Oui)
            :Score += 3;
        endif
        
        if (Le film contient un genre implicite déduit ?) then (Oui)
            :Score += 2;
        endif
        
        if (Le film est sur une plateforme de l'utilisateur ?) then (Oui)
            :Score += 5;
        endif
        
        :Score += (Note TMDB / 10);
        
        if (Score >= 2 ?) then (Oui)
            :Ajout d'un poids aléatoire (+ 0.0 à 1.5)\npour la diversité à chaque chargement;
            :Ajouter le film au tableau des résultats;
        else (Non)
            :Rejet du film;
        endif
    endif
endwhile (Non)

:Trier le tableau par Score décroissant;
:Sélectionner les 100 meilleurs films;
:Formater la réponse JSON;
:Retourner les recommandations au client;
stop

@enduml
