@startuml seq_watchlist
title Diagramme de Séquence — Ajout à la Watchlist

skinparam shadowing false
skinparam RoundCorner 5

actor "Utilisateur" as User
participant "React Frontend" as Front
participant "Backend Symfony" as API
database "MySQL" as DB

User -> Front: Clic "Ajouter à la Watchlist"
activate Front

Front -> API: PUT /api/profile { movieId } + JWT
activate API

API -> DB: Recherche du Film en BDD
activate DB
DB --> API: Résultat de recherche
deactivate DB

alt Film existant
    API -> DB: Création ou Mise à jour de la Watchlist (Statut: vu / a_voir)
    
    API --> Front: 200 OK (Profil à jour)
    Front --> User: Notification succès & Icône mise à jour
else Film introuvable
    API --> Front: 404 Not Found
    Front --> User: Notification erreur
end

deactivate API
deactivate Front
@enduml
