@startuml seq_auth
title Diagramme de Séquence — Authentification JWT & RGPD

skinparam shadowing false
skinparam RoundCorner 5

actor "Utilisateur" as User
participant "React Frontend" as Front
participant "Backend Symfony\n(API + Subscriber)" as API
database "MySQL" as DB
database "MongoDB" as Mongo

User -> Front: Saisie identifiants
activate Front

Front -> API: POST /api/login_check (x-consent-tracking)
activate API

API -> DB: Vérification des identifiants
activate DB
DB --> API: Résultat (User validé)
deactivate DB

alt Identifiants corrects
    API -> API: Génération du JWT
    
    opt Si consentement RGPD = true
        API -> Mongo: Enregistrement du log de connexion
    end
    
    API --> Front: 200 OK { token }
    Front -> Front: Stockage Token (LocalStorage)
    Front --> User: Connexion réussie (Redirection Accueil)
else Identifiants incorrects
    API --> Front: 401 Unauthorized
    Front --> User: Affichage message d'erreur
end

deactivate API
deactivate Front
@enduml
