@startuml uc_account
left to right direction
skinparam packageStyle rectangle

actor "Utilisateur Non Connecté" as Guest
actor "Utilisateur Connecté" as User

User -up-|> Guest

package "Accès Compte" {
    usecase "S'authentifier" as UC_Auth
    usecase "S'inscrire" as UC_Register

    usecase "Se déconnecter" as UC_Logout
    usecase "Supprimer son compte" as UC_Delete
}

Guest --> UC_Auth

UC_Auth <.. UC_Register : <<extends>>

User --> UC_Logout
User --> UC_Delete

@enduml
