@startuml
left to right direction
skinparam packageStyle rectangle

actor "Cron / CLI" as Cron
actor "API Streaming Availability" as SA
actor "API TMDB / OMDb" as TMDB

package "Backend & Processus Automatisés" {
    usecase "Mettre à jour la BDD\n(ImportMoviesCommand)" as UC_Import
    usecase "Récupérer infos films\net castings" as UC_Infos
    usecase "Récupérer disponibilité\nPlateformes" as UC_Plats
    
    usecase "Envoyer des rappels email\n(SendRemindersCommand)" as UC_Reminders
    usecase "Générer les notifications" as UC_GenNotifs
    
    usecase "Gérer les consentements RGPD" as UC_Privacy
    usecase "Journaliser connexion" as UC_Log
}

Cron --> UC_Import
Cron --> UC_Reminders

UC_Import ..> UC_Infos : <<include>>
UC_Import ..> UC_Plats : <<include>>
UC_Reminders ..> UC_GenNotifs : <<include>>

UC_Plats <-- SA
UC_Infos <-- TMDB

UC_Log ..> UC_Privacy : <<extend>>
note bottom of UC_Log
  Logué uniquement si
  l'utilisateur a consenti (RGPD)
end note

@enduml
