@startuml uc_movie
left to right direction
skinparam packageStyle rectangle

actor "Utilisateur" as Guest


package "Fiche Film" {
    usecase "Consulter la fiche d'un film" as UC_ViewMovie
    
    usecase "Consulter la note TMDB" as UC_Note
    usecase "Voir le casting" as UC_Cast
    usecase "Lire le synopsis" as UC_Synopsis
    usecase "Visionner la bande-annonce" as UC_Trailer
    usecase "Voir les plateformes de streaming" as UC_Plats
    usecase "Consulter les films similaires" as UC_Similars
}

Guest --> UC_ViewMovie

UC_ViewMovie ..> UC_Note : <<include>>
UC_ViewMovie ..> UC_Cast : <<include>>
UC_ViewMovie ..> UC_Synopsis : <<include>>
UC_ViewMovie ..> UC_Trailer : <<include>>
UC_ViewMovie ..> UC_Plats : <<include>>
UC_ViewMovie ..> UC_Similars : <<include>>

@enduml