@startuml
left to right direction
skinparam packageStyle rectangle

actor "Utilisateur" as User
actor "API Streaming Availability" as SA
actor "API TMDB" as TMDB
actor "Serveur (Cron)" as Cron



package "Accès Compte" as PkgAccount

package "RGPD & Confidentialité" as PkgPrivacy
package "Découverte et Recherche" as PkgSearch
package "Fiche Film" as PkgMovie
package "Gestion Personnel" as PkgPersonal
package "Notifications & Rappels" as PkgNotifs

package "Backend & API" as PkgBackend
        
User --> PkgPrivacy
User --> PkgSearch
User --> PkgMovie
User --> PkgPersonal
User --> PkgNotifs

PkgMovie ..> PkgAccount : <<include>>
PkgPersonal ..> PkgAccount : <<include>>
PkgNotifs ..> PkgAccount : <<include>>

PkgSearch ..> PkgBackend : <<use>>
PkgMovie ..> PkgBackend : <<use>>
PkgPersonal ..> PkgBackend : <<use>>
PkgNotifs ..> PkgBackend : <<use>>

PkgBackend <-- SA
PkgBackend <-- TMDB
PkgBackend <-- Cron
PkgNotifs <-- Cron
@enduml
