@startuml uc_search
left to right direction
skinparam packageStyle rectangle

actor "Utilisateur" as Guest


package "Découverte et Recherche" {
    usecase "Consulter la Page d'accueil" as UC_Home
    usecase "Rechercher un film" as UC_Search
    usecase "Parcourir le catalogue" as UC_Catalog
    
    usecase "Filtrer par genre" as UC_SearchGenre
    usecase "Filtrer par temps disponible" as UC_Time
}

Guest --> UC_Home
Guest --> UC_Search
Guest --> UC_Catalog

' Les filtres sont des extensions des fonctionnalités principales
' (ils sont optionnels)
UC_Time .up.> UC_Home : <<extend>>
UC_Time .up.> UC_Catalog : <<extend>>
UC_SearchGenre .up.> UC_Catalog : <<extend>>

@enduml
